---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: cadvisor
    image: centos/systemd:latest
    command: /sbin/init
    privileged: true
    volumes:
      # cadvisor needs the cgroup mount to access metrics
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
