---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: cadvisor
    image: eniocarboni/docker-rockylinux-systemd:9
    image_version: latest
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    groups:
      - extra_options
    volumes:
      # cadvisor needs the cgroup mount to access metrics
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu

provisioner:
  namefs/fs/cgroupcgroup: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
